# tasks file for haproxy
---
- name: install | add repository from PPA and install its signing key
  apt_repository:
    repo: "{{ haproxy_ppa }}"
    update_cache: true
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
  with_items:
    - "{{ haproxy_dependencies }}"
    - "{{ haproxy_install }}"
  tags:
    - haproxy-install
